FROM golang:1.21 AS builder

WORKDIR /app
COPY . .

ARG VERSION=v0.0.0
ARG COMMIT=none
ARG BUILD_DATE=unknown

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w -X 'main.version=${VERSION}' -X 'main.commit=${COMMIT}' -X 'main.date=${BUILD_DATE}'" \
    -o /out/app ./cmd/app

FROM scratch AS export-stage
COPY --from=builder /out/app /app
